### ISSUE TITLE
Why not use list to save policies?

### ISSUE THREAD

**Issue by RobotHuang** [casbin/redis-adapter#11]
We use string to save policies now. However, it is not convenient to add or delete policy(ies). So why not use list to save policies?

**Comment by hsluoyz** [comment]
@RobotHuang we can change to list. Can you elaborate more?

**Comment by RobotHuang** [comment]
@hsluoyz We might convert one policy to one JSON string and save this JSON string as a value of a list. When we add a new policy, we only need to find this list by key and push a new policy to this list, and the same goes for deletion.

**Comment by hsluoyz** [comment]
@RobotHuang sounds good. Go ahead with a PR.

**Comment by hsluoyz** [comment]
PR merged: https://github.com/casbin/redis-adapter/pull/10
