### ISSUE TITLE
i want to both have withkey and withpassword func

### ISSUE THREAD

**Issue by luo1324574369** [casbin/redis-adapter#16]
i want to init,such as this code

`a := NewAdapterWithOption(WithAddress("127.0.0.1:6379"),WithPassword("Abd12345"))`
	`

**Comment by hsluoyz** [comment]
@luo1324574369 why not use `a := redisadapter.NewAdapterWithPassword("tcp", "127.0.0.1:6379", "123")`?

**Comment by hsluoyz** [comment]
@closetool

**Comment by luo1324574369** [comment]
i want to both have key and password ,such as this code 

a := NewAdapterWithOption(WithAddress("127.0.0.1:6379"),WithKey("casbin_rules"),WithPassword("Abd12345"))

**Comment by closetool** [comment]
@luo1324574369 plz review https://github.com/casbin/redis-adapter/pull/22
