### ISSUE TITLE
Filtered policies support for casbin redis adapter

### ISSUE THREAD

**Issue by sujatapatnaik52** [casbin/redis-adapter#29]
Hi, 

I am using the `rbac_with_deny_model` for my usecase with casbin's redis adapter - https://github.com/casbin/redis-adapter. I have the following questions:

1. When the records are added via the casbin enforcer, does it store them all in memory as well? 
2. If the answer to number 1 is yes, then I read about performace and at some point the policies might grow which will cause the the `enforce()` calls to take more time. I can add another instance of casbin to handle this but I was looking to use policy subset loading feature. Apparently this does not exist for redis-adapter yet. Is there a way to add it or should I use only those backend storage libraries that support this?

Thank you.

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by sujatapatnaik52** [comment]
Hi, can you also answer the question about the policies being stored in-memory? and even if there is a filtered policy loading option, do I have to create a new enforcer every time I want to check the permissions?

**Comment by JalinWang** [comment]
@sujatapatnaik52 Hi~ Thanks for concerning about Casbin.

> 1. When the records are added via the casbin enforcer, does it store them all in memory as well?

For this question, the answer is true.

> Apparently this does not exist for redis-adapter yet.

I'll make a PR to support filtering in days.

> do I have to create a new enforcer with filtered policies every time I want to check the permissions?

No, you don't. You can divide enforcers by domains or use watcher to keep them synced.
