### ISSUE TITLE
I can't connect redis with password

### ISSUE THREAD

**Issue by fghosth** [casbin/redis-adapter#4]

**Comment by hsluoyz** [comment]
Hi @fghosth , what's your OS version and Redis version?

**Comment by hsluoyz** [comment]
@FatAngle, can you help troubleshoot this issue?

**Comment by FatAngle** [comment]
> @FatAngle, can you help troubleshoot this issue?

OK

**Comment by hsluoyz** [comment]
Hi @fghosth , this is fixed in: https://github.com/casbin/redis-adapter/commit/8c56da4d48d1531cfecd3878ba40789587c0a5a3, please use ``redisadapter.NewAdapterWithPassword("tcp", "127.0.0.1:6379", "your_redis_password")`` instead.
