### ISSUE TITLE
redis pool often has error

### ISSUE THREAD

**Issue by kissIce** [casbin/redis-adapter#41]
my project use this adapter and initlize redis pool when project start.   after 30 minutes when website send api request, 
the redis pool always report 'use of closed network connection' or 'write break pipe'.   

this is my code
<img width="1341" alt="image" src="https://github.com/casbin/redis-adapter/assets/18099374/c3a31c2b-02a8-4461-ba6d-bff4779f8a50">

i search this problem in internet.   it likes redisgo problem, so i goto redisgo github addr  and search in issues.   i find this reply

<img width="908" alt="image" src="https://github.com/casbin/redis-adapter/assets/18099374/f42b9921-a00f-470d-8378-3cea1931114d">

then i see the adapter origin code.  this adapter func NewAdapterWithPool() don't call defer conn.Close()
<img width="937" alt="image" src="https://github.com/casbin/redis-adapter/assets/18099374/d6f11678-33f9-42a6-99d5-2f51823b6ca2">

so i guess maybe is it make problem.  plz vaild it and fix it.  or if other problem plz tell me. thk

**Comment by hsluoyz** [comment]
@kissIce @marcozac hi, can you make a PR to fix it?

https://github.com/casbin/redis-adapter/commit/0cd40e5655c43a9787353fca24087fde2b571b58

**Comment by marcozac** [comment]
@kissIce @hsluoyz sorry for the delay!

The pool should be created before to pass it to `NewAdapterWithPool`, using (defer?) `pool.Close()` to close all resources. It frequently happens in the main function of the program.

For example:

```go
func main() {
	pool := &redis.Pool{
		// ...
	}
	defer pool.Close()

	a, err := redisadapter.NewAdapterWithPool(pool)
	if err != nil {
		// ...
	}

	cas := common.CasbinSt{}
	cas.RedisAdapter, _ = a

	// ...
}
```

The pooled conn il closed by the finalizer (`*Adapter` does not expose a `Close` method) instead.

Using `defer conn.Close()` in `NewAdapterWithPool` would close the connection when the function returns.

However, I'll take a look and some tests in the weekend.

I have a server in production using this adapter but I didn't find this issue. I'll try to replicate and fix it.

@kissIce if you want to share more details it would be very helpful!

Just a last (maybe intrusive) question: are you sure you need a pool? Based on the screenshot you shared, the same result would be accomplished with a simple connection leaving to the finalizer the responsibility to close it.

**Comment by cococolanosugar** [comment]
As far as i know, when you use a Redis connection pool, you should use the **pool.Get()** method every time you need to retrieve an available connection, rather than just getting it once during initialization.

And i make a PR([#43](https://github.com/casbin/redis-adapter/pull/43)), you can take a look.
