### ISSUE TITLE
go.mod set to forked repository

### ISSUE THREAD

**Issue by jimmy-ho** [casbin/redis-adapter#7]
Looks like the latest update of go.mod is set to a forked repository **github.com/fengjihua/redis-adapter** when it should be **module github.com/casbin/redis-adapter** - this causes the following error when trying to explicity use **v2**:

> github.com/casbin/redis-adapter/v2: github.com/casbin/redis-adapter/v2@v2.0.0: parsing go.mod:
>         module declares its path as: github.com/fengjihua/redis-adapter/v2
>                 but was required as: github.com/casbin/redis-adapter/v2

I assume this was in error when the changes were merged in.

**Comment by hsluoyz** [comment]
@jimmy-ho can you make a PR to fix it?

**Comment by jimmy-ho** [comment]
Sure let me go ahead and issue a quick fix for this

**Comment by jimmy-ho** [comment]
PR is now available to fix this.

**Comment by hsluoyz** [comment]
Merged.

**Comment by jimmy-ho** [comment]
@hsluoyz if you can tag up a new v2.0.1 so go mod can pick this up?

**Comment by hsluoyz** [comment]
Done: https://github.com/casbin/redis-adapter/releases/tag/v2.0.1

**Comment by jimmy-ho** [comment]
Thanks @hsluoyz confirmed all working now.
