### ISSUE TITLE
Adapter is not compliant with BatchAdapter interface

### ISSUE THREAD

**Issue by WesleyBatista** [casbin/redis-adapter#9]
Trying to use this library with casbin@v2.19.7 but it seems to be a bit outdated.

The part of the code that fails:

```go
	policiesRules := [][]string{
		{"admin", "domain1", "*"},
		{"anonymous", "*", "/"},
	}

	Enforcer.AddNamedPolicies("p", policiesRules)
```

output:
```
panic: interface conversion: *redisadapter.Adapter is not persist.BatchAdapter: missing method AddPolicies
```

This is the [persist.BatchAdapter interface](https://github.com/casbin/casbin/blob/d0d65d828c784211a47c23f9cc63b7429da0287e/persist/batch_adapter.go#L18) needed to be implemented, and seems to be easy to do it, but I am unfortunately still learning go :disappointed:

**Comment by hsluoyz** [comment]
PR merged and new version v2.1.0 released: https://github.com/casbin/redis-adapter/releases/tag/v2.1.0
